import {chromium} from '@playwright/test';
import fs from 'node:fs';
const root=new URL('../',import.meta.url).pathname.replace(/^\/(\w:)/,'$1');
const password=process.env.DEMO_PASSWORD;
if(!password)throw new Error('Set DEMO_PASSWORD for browser verification');
fs.mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},...(process.env.RECORD_VIDEO==='1'?{recordVideo:{dir:'test-results/video',size:{width:1440,height:1000}}}:{})});
const page=await context.newPage();page.setDefaultTimeout(20000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const steps=[];const mark=s=>{steps.push(s);console.log('PASS',s)};
try{
 await page.goto('http://127.0.0.1:8000');
 await page.getByRole('heading',{name:'Welcome back.'}).waitFor();
 await page.screenshot({path:'test-results/login-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'New here? Create an account'}).click();
 const username='verify-'+Date.now();
 await page.getByLabel('Username',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('heading',{name:'A good day to learn something.'}).waitFor();mark('Registration and empty dashboard');
 await page.getByRole('button',{name:'Create space',exact:true}).click();
 await page.getByLabel('Name',{exact:true}).fill('Biology · verification');await page.getByLabel('Description',{exact:true}).fill('A real browser verification workspace.');
 await page.getByRole('button',{name:'Create space',exact:true}).last().click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'New project',exact:true}).click();
 await page.getByLabel('Name',{exact:true}).fill('Photosynthesis learning loop');await page.getByLabel('Description',{exact:true}).fill('Live end-to-end verification using the demo study material.');await page.getByLabel('Learning goal',{exact:true}).fill('Explain photosynthesis, light reactions, and the Calvin cycle.');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await page.getByRole('tab',{name:'Materials',exact:true}).click();mark('Create Space and Project');
 await page.getByLabel('Upload PDF').setInputFiles('../docs/demo-material.pdf');
 await page.getByText('ready',{exact:true}).waitFor({timeout:180000});mark('PDF upload and persistent live processing');
 await page.screenshot({path:'test-results/materials-desktop.png',fullPage:true});
 await page.waitForTimeout(16000);await page.getByRole('tab',{name:'Tutor',exact:true}).click();
 await page.getByLabel('Ask your tutor').fill('Where does the Calvin cycle occur?');await page.getByRole('button',{name:'Send question'}).click();
 await page.locator('.citations a').first().waitFor({timeout:160000});
 const href=await page.locator('.citations a').first().getAttribute('href');
 if(!href.includes('#page='))throw new Error('Missing page citation');
 const pdf=await context.request.get(new URL(href,'http://127.0.0.1:8000').href);if(!pdf.ok())throw new Error('Citation file unavailable');mark('Live grounded Tutor and authenticated page citation');
 await page.getByLabel('Ask your tutor').fill('What is the current price of bitcoin?');await page.getByRole('button',{name:'Send question'}).click();
 await page.getByText(/enough evidence|Insufficient evidence/).first().waitFor({timeout:90000});mark('Unsupported question abstains');
 await page.screenshot({path:'test-results/tutor-desktop.png',fullPage:true});
 await page.waitForTimeout(16000);await page.getByRole('tab',{name:'Quiz',exact:true}).click();await page.getByRole('button',{name:'Start practice',exact:true}).click();
 await page.locator('.option').first().waitFor({timeout:160000});await page.locator('.option').first().click();await page.getByRole('button',{name:'Check my understanding',exact:true}).click();
 await page.locator('.feedback').waitFor({timeout:160000});mark('Live adaptive MCQ and feedback');
 await page.waitForTimeout(16000);await page.getByRole('button',{name:'Choose next practice'}).click();await page.getByRole('button',{name:/Open-ended Explain/}).click();await page.getByRole('button',{name:'Start practice',exact:true}).click();
 await page.getByLabel('Your explanation',{exact:true}).waitFor({timeout:160000});await page.getByLabel('Your explanation',{exact:true}).fill('Photosynthesis converts light energy to chemical energy. Chlorophyll captures light in the thylakoid membranes. Water is split and oxygen is released. ATP and NADPH power carbon fixation in the Calvin cycle in the stroma. Rubisco fixes carbon dioxide, and G3P can form sugars or regenerate RuBP. Light intensity, carbon dioxide and temperature can limit the rate.');
 await page.waitForTimeout(16000);await page.getByRole('button',{name:'Check my understanding',exact:true}).click();await page.locator('.feedback').waitFor({timeout:160000});
 if(await page.locator('.criterion').count()<2)throw new Error('Missing rubric feedback');mark('Live open-ended grading with criterion feedback');
 await page.screenshot({path:'test-results/quiz-desktop.png',fullPage:true});
 await page.getByRole('tab',{name:'Growth',exact:true}).click();await page.getByRole('heading',{name:'Mastery evidence over time'}).waitFor();await page.locator('tbody tr').first().waitFor();mark('Persisted mastery, growth and recommendations');
 await page.screenshot({path:'test-results/growth-desktop.png',fullPage:true});
 await page.getByRole('tab',{name:'Analytics',exact:true}).click();await page.getByRole('heading',{name:'AI usage & reliability'}).waitFor();mark('Project analytics');
 await page.getByRole('button',{name:'Global analytics',exact:true}).click();await page.getByRole('heading',{name:'Your learning, at a glance.'}).waitFor();mark('Global analytics');
 await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('heading',{name:'A good day to learn something.'}).waitFor();await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/home-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile page has horizontal overflow');
 await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('button',{name:'Global analytics',exact:true}).click();await page.getByRole('heading',{name:'Your learning, at a glance.'}).waitFor();await page.screenshot({path:'test-results/analytics-mobile.png',fullPage:true});mark('Mobile layout and navigation');
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('button',{name:'Admin dashboard',exact:true}).click();await page.getByRole('heading',{name:'Background jobs & failures'}).waitFor();
 await page.getByLabel('user',{exact:true}).selectOption({label:username});await page.getByRole('heading',{name:'Assessment evidence'}).waitFor();await page.getByLabel('Activity type',{exact:true}).selectOption('assessment_completed');await page.getByLabel('from',{exact:true}).fill(new Date().toISOString().slice(0,10));await page.waitForTimeout(800);mark('Admin user drill-down, jobs, AI usage and evaluations');
 await page.screenshot({path:'test-results/admin-desktop.png',fullPage:true});
 if(errors.length)throw new Error(errors.join('; '));
 fs.writeFileSync('../docs/browser-results.json',JSON.stringify({mode:'live; no mocked network calls',created:new Date().toISOString(),passed:steps,consoleErrors:errors},null,2));
}catch(e){await page.screenshot({path:'test-results/failure.png',fullPage:true});fs.writeFileSync('../docs/browser-results.json',JSON.stringify({passed:steps,error:String(e),consoleErrors:errors},null,2));throw e}
finally{await context.close();await browser.close()}
