import {useEffect,useState} from 'react';
import {api} from './api';
type Data=Record<string,any>;
const pct=(n:number|null)=>n==null?'Not enough evidence':`${Math.round(n*100)}%`;
export function Insights({projectId}:{projectId:number}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;const load=()=>api(`/projects/${projectId}/insights/`).then(x=>{if(alive)setData(x)}).catch(e=>{if(alive)setError(e.message)});load();const timer=setInterval(load,4000);return()=>{alive=false;clearInterval(timer)}},[projectId]);
 async function refresh(){setBusy(true);setError('');try{setData(await api(`/projects/${projectId}/insights/`,'POST'))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const info=data?.insights;
 return <section className="card spaced"><div className="section-heading"><div><h3>Learning insights</h3><p className="muted">Calculated in the background from your saved assessments.</p></div><button className="secondary" disabled={busy||['queued','processing'].includes(data?.job?.status)} onClick={refresh}>{busy?'Queuing…':data?.job?.status==='failed'?'Retry insights':'Refresh insights'}</button></div>{error&&<p role="alert" className="error">{error}</p>}{data?.job&&<p role="status"><span className={'status '+data.job.status}>{data.job.status}</span> · Attempt {data.job.attempts}{data.job.error&&` · ${data.job.error}`}</p>}{info?<><div className="insight-metrics"><div><small>Recent 5 average</small><strong>{pct(info.recent_score)}</strong></div><div><small>Previous 5 average</small><strong>{pct(info.previous_score)}</strong></div><div><small>Change</small><strong>{info.score_change==null?'Baseline needed':`${info.score_change>=0?'+':''}${Math.round(info.score_change*100)} pp`}</strong></div></div><p>{info.method}</p><h4>Recurring learning gaps</h4>{info.recurring_gaps.length?info.recurring_gaps.map((g:Data)=><p key={g.name}>{g.name} <span className="pill">{g.count} attempts</span></p>):<p>No recurring gaps in the recorded evidence.</p>}<small>Updated {new Date(info.generated_at).toLocaleString()} · {info.evidence_count} evidence points</small></>:<p>No background insight snapshot yet. Complete an assessment or refresh to calculate one.</p>}</section>
}
export function Breakdown({rows}:{rows:Data[]}){return <section className="card spaced"><h3>Where performance changes</h3><p className="muted">Assessment averages by concept, question type and difficulty in the selected period.</p><div className="table-wrap"><table><thead><tr><th>Concept / project</th><th>Type</th><th>Difficulty</th><th>Attempts</th><th>Average score</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.question__concept__name}<small className="block">{r.question__project__name}</small></td><td>{r.question__kind==='mcq'?'Multiple choice':'Open ended'}</td><td>{r.question__difficulty}</td><td>{r.attempts}</td><td><div className="score-track" aria-label={`Average score ${pct(r.score)}`}><span style={{width:`${r.score*100}%`}}/></div>{pct(r.score)}</td></tr>)}</tbody></table>{!rows.length&&<p>No assessment evidence in this period.</p>}</div></section>}
export function Trace({usage}:{usage:Data}){return <details className="trace"><summary>Inspect trace</summary><small className="block">{usage.trace_id}</small>{usage.spans?.length?usage.spans.map((s:Data,i:number)=><p key={i}><strong>{s.stage}</strong> · {s.status||s.provider||'Recorded'}{s.attempt&&` · attempt ${s.attempt}`}{s.latency_ms!=null&&` · ${s.latency_ms} ms`}{s.schema&&` · ${s.schema}`}{s.source_ids&&` · ${s.source_ids.length} validated sources`}</p>):<p>This request predates detailed tracing.</p>}</details>}
export function DocumentDetails({material}:{material:Data}){return <>{material.stage&&<small className="block">Stage: {material.stage}{material.status==='queued'&&material.attempts>0?` · Retry after ${new Date(material.retry_at).toLocaleTimeString()}`:''}</small>}{(material.structure?.pages?.length>0||material.history?.length>0)&&<details className="trace"><summary>Extraction & retry details</summary>{material.structure?.pages?.map((p:Data)=><p key={p.page}><a href={`/api/materials/${material.id}/file/#page=${p.page}`} target="_blank" rel="noreferrer">Page {p.page}</a> · {p.characters} characters · {p.tables} tables · {p.images} images{p.heading&&` · ${p.heading}`}</p>)}{material.history?.map((h:Data,i:number)=><p key={i}>Attempt {h.attempt}: {h.status}{h.error&&` · ${h.error}`}</p>)}</details>}</>}
