# Generated by Django 5.2.17 on 2026-09-18 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusage',
            name='spans',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='job',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='stage',
            field=models.CharField(default='extraction', max_length=30),
        ),
        migrations.AddField(
            model_name='material',
            name='structure',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='InsightJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=100)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease', models.UUIDField(null=True)),
                ('available', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('result', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_jobs', to='study.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'revision'), name='unique_insight_revision')],
            },
        ),
        migrations.CreateModel(
            name='RetrievalCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('chunk_ids', models.JSONField(default=list)),
                ('expires', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='unique_retrieval_cache')],
            },
        ),
    ]
